name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master # or the branch where your changes are

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install Dependencies
        run: npm install # or any other package manager command

      - name: Build
        run: npm run build # or any command to build your app

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages # or any other branch you want to deploy to
          folder: build # or the folder containing your built app
          token: ${{ secrets.GITHUB_TOKEN }}
